Update nextjs.yml

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -29,15 +29,16 @@ jobs:
             echo "manager=yarn" >> $GITHUB_OUTPUT
             echo "command=install" >> $GITHUB_OUTPUT
             echo "runner=yarn" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
+             exit 0
+            elif [ -f "${{ github.workspace }}/package.json" ]; then
+           echo "manager=npm" >> $GITHUB_OUTPUT
             echo "command=ci" >> $GITHUB_OUTPUT
-            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-            exit 0
+           echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+           exit 0
           else
-            echo "Unable to determine package manager"
-            exit 1
+           echo "Unable to determine package manager"
+          exit 1
+          fi # Add this line to close the if statement
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
